apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cert-manager
  namespace: bigbang
spec:
  gitImplementation: go-git
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
    !/chart/tests/scripts/*.sh
  interval: 2m
  ref:
    branch: certs-and-issuers
  timeout: 60s
  url: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/cert-manager.git
  {{- include "gitCreds" . | nindent 2 }}
