apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: ./chart
      interval: 5m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: cert-manager
        namespace: cert-manager
      version: '*'
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 2m
  rollback:
    cleanupOnFail: true
    timeout: 10m
  targetNamespace: cert-manager
  test:
    enable: false
  timeout: 10m
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  dependsOn:
  - name: istio
    namespace: bigbang
  values:
    certificates: 
    - name: public-cert
      namespace: istio-system
      dnsNames:
      - "*.{{ .Values.domain }}"
    issuer:
      enabled: true
      name: default-issuer
      email: dns01-solver@leapfrogai.iam.gserviceaccount.com
      dnsZones:
      - {{ .Values.domain | quote }}
      dns01: cloudDNS
      credentials: {{ .Values.credentials | quote }}
