---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: credentials-copy
  namespace: cert-manager
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/defenseunicorns/credentials-copy
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: credentials
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: credentials-copy
  interval: 1m0s
  dependsOn:
  - name: istio
    namespace: bigbang
  values:
    credentials:
    - credential:
        source: 
          name: private-registry
          namespace: istio-system
        destination:
          name: private-registry
          namespace: cert-manager