apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  gitImplementation: go-git
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
    !/chart/tests/scripts/*.sh
  interval: 2m
  ref:
    branch: master
  timeout: 60s
  url: https://github.com/kubernetes-sigs/external-dns