apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: domain-manager
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
  interval: 10m
  url: https://github.com/defenseunicorns/domain-manager
  ref:
    branch: main
