apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: domain-manager
spec:
  targetNamespace: bigbang
  releaseName: domain-manager
  interval: 10m
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: domain-manager
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: domain-manager
    - kind: Secret
      name: domain-manager-optional
      optional: true
