configurations:
- transformer.yaml

namespace: bigbang

commonLabels:
  owner: bigbang

resources:
  - gitrepository.yaml
  - helmrelease.yaml

# Flux combines secrets and configmaps in `valuesFrom`.  Kustomize
# cannot distinguish between them when applying suffixes.  Therefore,
# the secrets must have different names than the configmaps
secretGenerator:
  - name: domain-manager
    behavior: create
    literals:
    - values.yaml=